export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_PLAYERS_PENDING = 'REQUEST_PLAYERS_PENDING';
export const REQUEST_PLAYERS_SUCCESS = 'REQUEST_PLAYERS_SUCCESS';
export const REQUEST_PLAYERS_FAILED = 'REQUEST_PLAYERS_FAILED';
